language: python

cache:
  directories:
  - $HOME/nats-server

python:
  - 3.6

before_install:
  - bash ./script/install_nats.sh

before_script:
  - export PATH=$HOME/nats-server:$PATH

install:
  - pip install -e .[nkeys]

script:
  - make ci
  
notifications:
  email: false

sudo: false
dist: trusty

# Temporary for Python 3.7
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
